/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "CONNECTED": "CONNECTED",
    "DESCRIPTION": "The ping monitor allows you to monitor the connection status (in terms of latency) between localhost and a single remote address, specified below.",
    "DISK ACTIVITY": "DISK ACTIVITY",
    "Done": "Done",
    "IN": "IN",
    "LATENCY": "LATENCY",
    "NETWORK": "NETWORK",
    "OUT": "OUT",
    "PROCESSOR": "PROCESSOR",
    "REMOTE_ADDR": "REMOTE ADDRESS"
};

